language: node_js
node_js:
  - "node"
  - "lts/*"

install: true

cache:
  yarn: true
  directories: node_modules

before_script: yarn install && yarn typed

script:
  - yarn build
  - yarn lint
  - yarn test

after_success: yarn coverage
